# Machine Learning:
- Deep Learning.
- Neuron & Perceptron Implementation.

In [16]:
import torch
import torch.nn as nn
print(torch.__version__)

2.5.1


In [17]:
import torch
import torch.nn as nn

## Seed a manual constant value:

In [18]:
torch.manual_seed(42)

## Input Creation:

In [19]:
inputs = torch.tensor([1.0, 2.0, 3.0]) # x1, x2 & x3 | 1D-Inputs

## Neuron Creation:

In [20]:
neuron = nn.Linear(in_features = 3, out_features = 1)

## Output:

In [21]:
output = neuron(inputs)

In [22]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

## Verifying Outputs: Using Foemule

In [23]:
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

## Automaticly Verification:

In [24]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [25]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)