In [1]:
import torch
import torch.nn as nn

In [14]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])

In [15]:
neuron = nn.Linear(in_features=3, out_features=1)

In [16]:
output = neuron(inputs)

In [17]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [18]:
# verify ... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [7]:
neuron.bias

Parameter containing:
tensor([-0.3646], requires_grad=True)